### ISSUE TITLE
Hi! How to perform test without Label_2 folder, like in KITTI testing?

### ISSUE THREAD

**Issue by oljike** [zhixinwang/frustum-convnet#10]

**Comment by harish-kamath** [comment]
Hi, I have the same question, and am beginning to doubt how this model even works looking through the code

**Comment by zhixinwang** [comment]
Hi, for the test set, you can set the `TEST.DATASET=test` instead default setting `val`. For the test set without ground truth annotations, we only save the prediction results without evaluation.

**Comment by gujiaqivadin** [comment]
> Hi, for the test set, you can set the `TEST.DATASET=test` instead default setting `val`. For the test set without ground truth annotations, we only save the prediction results without evaluation.

But in test dataset we don’t have the 2d rgb detection results .txt,  we can not get the related frustum.

**Comment by harish-kamath** [comment]
I think the point is that we have no label_2 folder in testing to create the pickle files for TEST.DATASET, correct? In this case how do we make the pickle file to run inference on?

**Comment by zhixinwang** [comment]
@harish-kamath If you want to get the results of test set,  you need to use a  2D detector to get the results of test set firstly, and save the results as the format in kitti/rgb_detections//rgb_detection_train.txt. And then use the kitti/prepare_data.py to prepare the pickle file( generate the pickle file from rgb_detection_val.txt). You need to change some of the code, including the path or image set file.

**Comment by zhixinwang** [comment]
@gujiaqivadin For the test set, we use the 2D detectors provided by [RRC](https://github.com/xiaohaoChen/rrc_detection)  for car category.
