### ISSUE TITLE
RuntimeError: cuda runtime error (98) : invalid device function at query_depth_point_cuda_kernel.cu:85

### ISSUE THREAD

**Issue by Ben940315** [zhixinwang/frustum-convnet#11]
Hi， After I run car_train.sh. I get the error "THCudaCheck FAIL file=query_depth_point_cuda_kernel.cu line=85 error=98 : invalid device function" and "RuntimeError: cuda runtime error (98) : invalid device function at query_depth_point_cuda_kernel.cu:85". Can u tell the solutions? thanks.

**Comment by zhixinwang** [comment]
You might not have the GPU set up correctly, such as, your environment variable `export CUDA_VISIBLE_DEVICES=0` is not a valid gpu id.

**Comment by Ben940315** [comment]
thanks for your answer. I have trained the model .However when I tested the model. I got the error:ERROR: Couldn't read: 006813.txt of ground truth. Please write me an email.  So  how can I solve it？ thanks

**Comment by zhixinwang** [comment]
Same issue as #2. Please check your dataset label path.

**Comment by Ben940315** [comment]
Thank you.However,when I read the paper, I was a little confused about the parameter u [0.25,0.5,1.0,2.0,]. What do these four numbers mean? If it is the height of each frustum segment, you mentioned earlier that the frustum is evenly segmented. Can you give some specific details? thanks again.

**Comment by zhixinwang** [comment]
We use four kinds of resolutions in this experiment, so we have totally four numbers for different height of frustum.

**Comment by Ben940315** [comment]
Thanks. So for the frusutm,there is more than 4 segments? Because in reading the previous version of the paper, there are four segments.

**Comment by RocketFlash** [comment]
@Ben940315 How did you fixed the problem ?
