### ISSUE TITLE
How to visualize the output (with bounding boxes)

### ISSUE THREAD

**Issue by aks1087** [zhixinwang/frustum-convnet#12]
Hi @zhixinwang,
Thanks very much for the code!  I have a below query.
How to visualize the output (with bounding boxes). I want to see how the dimensions of boxes look like?
please share the way or any command/scripts if possible.

**Comment by zhixinwang** [comment]
@aks1087 You can refer the visualization code from [F-pointnets](https://github.com/charlesq34/frustum-pointnets/tree/master/mayavi), or directly use code from [kitti_object_vis](https://github.com/kuixu/kitti_object_vis).

**Comment by Jihun-Kim-kmu** [comment]
I wonder if you got a bounding box with F-pointnets.
If you succeeded, could you tell me how to get bounding box
