### ISSUE TITLE
ERROR: Couldn't read: 004391.txt of ground truth.

### ISSUE THREAD

**Issue by fxy2012** [zhixinwang/frustum-convnet#2]
Hello,  
   zhixin, I have ran the codes follow your step. But I had a problem when I used the testing codes, which is as follows.
    <python train/test_net_det.py --cfg cfgs/det_sample.yaml OUTPUT_DIR output/car_train TEST.WEIGHTS output/car_train/model_0050.pth>
    An error occured :
    ERROR: Couldn't read: 004391.txt of ground truth. Please write me an email!
    An error occured while processing your results.

    Could you please help me solve it?

**Comment by lhyfst** [comment]
please double check your dataset and your label path. Can you find label files by the path in your code?

**Comment by fxy2012** [comment]
@lhyfst Thank you for your reply! 
I saved KITTI files in other folder, and I modified the path to get KITTI data in the codes.  This error seemed to be solved, but a new error occurred:
`sh: 1: pdfcrop: not found`

**Comment by fxy2012** [comment]
@lhyfst Thank you for your reply!
And I have found that some of `.txt` files in`output/car_train/val_nms/result/data` are empty. Is there something wrong with my training，or do you know the reasons?

**Comment by lhyfst** [comment]
yes, some frames just do not have any cars. If you still suspect there are some problems, you had better visualize your prediction.

**Comment by fxy2012** [comment]
@lhyfst  I've got it. Many thanks!
