### ISSUE TITLE
How to train model on custom dataset?

### ISSUE THREAD

**Issue by RocketFlash** [zhixinwang/frustum-convnet#21]
Hello, @zhixinwang !
Thank you for your great work!  Is it possible to train frustum-convnet on a custom dataset? What and where should I change in code?

**Comment by zhixinwang** [comment]
@RocketFlash  Current our code is mainly designed for KITTI dataset. If you want to use it for a custom dataset, the best way is to prepare the data according to KITTI format. For different categories in custom dataset, you can modify the information in `datasets/dataset_info.py`. The most important thing is you should care more about on the different coordinates.  Contributions are welcomed to support  other datasets.

**Comment by RocketFlash** [comment]
@zhixinwang Thank you for the answer! I have another question: is it possible to train the network without camera data ? I mean if I have only lidar scans and 3D bboxes ? How is it better then to generate frustums ?

**Comment by zhixinwang** [comment]
Our method leverages mature 2D detectors in RGB images to provide reliable frustum proposals. 
If you don't have camera data, our method may not have an advantage.  However,  there is a possible method to generate frustum without RGB images. Try to first generate frustum proposals from range-view point cloud data. I do not have related experiments about this. You can try by yourself and welcome to share your experiment results.
