### ISSUE TITLE
Boost version in box_ops.h

### ISSUE THREAD

**Issue by jytime** [zhixinwang/frustum-convnet#22]
Hi Zhixin,

I met the same problem as @zstu-lly stated in https://github.com/zhixinwang/frustum-convnet/issues/16 . He solved it by updating the boost library from 1.53 to 1.58.

However, I am conducting experiments on a server shared by many people. I do not have access to install a new boost library. Would you have any suggestions if I want to modify the related codes into boost 1.53? Or any other solutions?

Best Regards,
Jianyuan

**Comment by zstu-lly** [comment]
Hi, I also use a server shared by many people, and I don’t have root . So I compile boost and install it under my own directory.

**Comment by jytime** [comment]
> Hi, I also use a server shared by many people, and I don’t have root . So I compile boost and install it under my own directory.

Thank you linye. I would try it.

**Comment by jytime** [comment]
Hi @zstu-lly,

According to [ boost official website](https://www.boost.org/doc/libs/1_58_0/more/getting_started/unix-variants.html#easy-build-and-install), I have downloaded boost 1.58 and built it from source. I also specify the boost path by commant
(export LD_LIBRARY_PATH=/mnt/lustre/wangjianyuan/frustum-convnet/lib_boost/include/boost). However, it still reports the same error. 

May I ask is there anything else I should do? 

Best.

**Comment by zhixinwang** [comment]
Recommend  using anaconda to create python environment and install dependencies.

**Comment by jytime** [comment]
solved by modifying make.sh:
`g++ -std=c++11 -shared -o box_ops_cc.so box_ops.cc -fPIC -O3 ${include} -I/path/to/boost/include/`

By the way, this is the conflict raised by the C++ dependencies and the python anaconda environment does not affect.
