### ISSUE TITLE
How to train model on multiple classes?

### ISSUE THREAD

**Issue by RocketFlash** [zhixinwang/frustum-convnet#26]
Hello, @zhixinwang ! 
I want to train model on multiple classes. I found that parameter **num_classes** not used in **PointNetDet** , and classification and regression outputs always same sized:
`output_size = 3 + num_bins * 2 + NUM_SIZE_CLUSTER * 4`
`self.reg_out = nn.Conv1d(768, output_size, 1)`
`self.cls_out = nn.Conv1d(768, 2, 1)` 

How can I modify the outputs to train the network in 3 or more classes?

**Comment by zhixinwang** [comment]
Refer to #28. Close.
