### ISSUE TITLE
How and where in the code you used hard, medium and easy criteria

### ISSUE THREAD

**Issue by ghost** [zhixinwang/frustum-convnet#29]
I want to know where in the code you classified data based on hard, medium, and easy for the evaluation.  I understand based on the Kitti website it should be used-> http://www.cvlibs.net/datasets/kitti/eval_object.php
but could you please point out in the code where and how this was used after predictions are captured? A quick response will be highly appreciated.

**Comment by zhixinwang** [comment]
Please refer to office evaluation code https://github.com/zhixinwang/frustum-convnet/blob/eb8e67fbbf21f21aba4616d513957c4a8bc6f9fd/train/kitti_eval/evaluate_object_3d_offline.cpp
