### ISSUE TITLE
Python can't open file kitti-object-eval-python

### ISSUE THREAD

**Issue by sarimmehdi** [zhixinwang/frustum-convnet#35]
Hello. I get the following error towards the end when I run `scripts/eval_pretrained_models.sh`. Please tell me how to fix this, thanks!
```
python ../kitti-object-eval-python/evaluate.py evaluate --label_path=data/kitti/training/label_2/ --result_path=pretrained_models/car_refine/val_nms/result/data --label_split_file=./data/kitti/val.txt --current_class=0 --coco=False 2>&1 | tee -a  pretrained_models/car_refine/val_nms/result/data/../log_test_new.txt
python: can't open file '../kitti-object-eval-python/evaluate.py': [Errno 2] No such file or directory
```

**Comment by sarimmehdi** [comment]
I fixed this problem by downloading all files from here: https://github.com/traveller59/kitti-object-eval-python
and putting them in kitti-object-eval-python folder outside the frustum folder

**Comment by Jihun-Kim-kmu** [comment]
I have a question.  Can you tell me your working environment?
My environment : Ubuntu-16.04 CUDA-9.0, CUDNN-7.0.5, Python-3.7.0, PyTorch-1.0.0, tensorboard-2.0.0 tensorflow-2.0.0 and anaconda. when I run this code $ python train/train_net_det.py --cfg cfgs/det_sample.yaml OUTPUT_DIR output/car_train
this error occur. 
I am planning to reinstall Ubuntu.

**Comment by sarimmehdi** [comment]
Please download this https://github.com/traveller59/kitti-object-eval-python and unzip it outside the frustum directory. If you do not wish to use the evaluation script, please go here https://github.com/zhixinwang/frustum-convnet/blob/fd0e35e18e435e7bc35bead2da9c3476b1ce94b1/train/test_net_det.py#L311

and put the following code:
```
    if 'test' not in cfg.TEST.DATASET:
        # evaluate_py_wrapper(result_dir)
        # evaluate_cuda_wrapper(output_dir, cfg.TEST.DATASET)
        print('no')
    else:
        logger.info('results file save in  {}'.format(result_dir))
        os.system('cd %s && zip -q -r ../results.zip *' % (result_dir))
```

**Comment by Jihun-Kim-kmu** [comment]
Thank you sarimmehdi. Thanks to you, I was able to resolve the error.
I have one more question.
Do you know how to get a bounding box as a result of the model?

**Comment by sarimmehdi** [comment]
results are stored in `/frustum-convnet/pretrained_models/car/val_nms/result/data`
frustum-convnet is where I git cloned this repository

**Comment by Jihun-Kim-kmu** [comment]
yes data were sotred in that folder. but I'd like to visualize the results.
![image](https://user-images.githubusercontent.com/65701965/89125289-5f1eb200-d518-11ea-89d3-2d870a415335.png)
like this

**Comment by sarimmehdi** [comment]
```
import pandas as pd
import cv2
import numpy as np

def plot_3d_bbox(img, calib, bbox3d_center, bbox3d_dims, bbox3d_roty):
    box_3d = []
    box_pts = []

    for i in [1, -1]:
        for j in [1, -1]:
            for k in [0, 1]:
                point = np.copy(bbox3d_center)
                point[0] = bbox3d_center[0] + i * bbox3d_dims[1] / 2 * 
                           np.cos(-bbox3d_roty + np.pi / 2) + (j * i) * bbox3d_dims[2] / 2 * 
                           np.cos(-bbox3d_roty)
                point[2] = bbox3d_center[2] + i * bbox3d_dims[1] / 2 * 
                           np.sin(-bbox3d_roty + np.pi / 2) + (j * i) * bbox3d_dims[2] / 2 * 
                           np.sin(-bbox3d_roty)
                point[1] = bbox3d_center[1] - k * bbox3d_dims[0]

                point = np.append(point, 1)
                box_pts.append(point)
                box_3d.append(get_img_pt(point, calib))

    for i in range(4):
        point_1_ = box_3d[2 * i]
        point_2_ = box_3d[2 * i + 1]
        cv2.line(img, (point_1_[0], point_1_[1]), (point_2_[0], point_2_[1]), (0,0,255), 1)

    for i in range(8):
        point_1_ = box_3d[i]
        point_2_ = box_3d[(i + 2) % 8]
        cv2.line(img, (point_1_[0], point_1_[1]), (point_2_[0], point_2_[1]), (0,0,255), 1)

    point_6_, point_0_, point_7_, point_1_ = box_3d[6], box_3d[0], box_3d[7], box_3d[1]

    cv2.line(img, (point_6_[0], point_6_[1]), (point_1_[0], point_1_[1]), (0,0,255), 1)
    cv2.line(img, (point_0_[0], point_0_[1]), (point_7_[0], point_7_[1]), (0,0,255), 1)

#imgs_folder, calib_files_folder, label_folder is where your left images, calibration files and label files are
frame = '000000.png'
calib_file = '000000.txt'
label_file = '000000.txt'
img = cv2.imread(os.path.join(imgs_folder, frame))

clb_file = open(os.path.join(calib_files_folder, calib_file))
clb = {}
for line in clb_file:
    calib_line = line.split(':')
    if len(calib_line) < 2:
        continue
    key = calib_line[0]
    value = np.array(list(map(float, calib_line[1].split())))
    value = value.reshape((3, -1))
    clb[key] = value

label = pd.read_csv(os.path.join(label_folder, label_file), sep=" ", header=None)
label = list(label.to_numpy())[0]

label_bbox3d_dims = gt[8:11]
label_bbox3d_loc = gt[11:14]
#last item is score and second last item is the rotation angle in generated label file
#in ground truth file, last item is the rotation angle
label_roty = gt[-2]              

plot_3d_bbox(img, clb, label_bbox3d_loc, label_bbox3d_dims, label_roty)
```

**Comment by Jihun-Kim-kmu** [comment]
frustum-convnet/output/car_train/val_nms/result/data/000001.txt format like this
![image](https://user-images.githubusercontent.com/65701965/89146868-fecb5700-d58f-11ea-8d7e-6fd951c60019.png)
And I launced python viz.py
![image](https://user-images.githubusercontent.com/65701965/89146936-34704000-d590-11ea-9671-d119cd978f49.png)
Do I need to modify the file code?

**Comment by Jihun-Kim-kmu** [comment]
Is the code you uploaded visualized in other models?

**Comment by Jihun-Kim-kmu** [comment]
Could you tell me if the code you posted above is working on this program?

**Comment by Jihun-Kim-kmu** [comment]
sorry but i have a question 
you solved this error?
ModuleNotFoundError: No module named 'second'
