### ISSUE TITLE
Whats the use of 'frustum_caronly_val_rgb_detection.pickle'

### ISSUE THREAD

**Issue by Niceday99** [zhixinwang/frustum-convnet#4]
Hi Zhixin,

What is the use of 'frustum_caronly_val_rgb_detection.pickle' dataset? It seems I can train the network without this file. 

Meanwhile, how to generate 'kitti/rgb_detections/rgb_detection_val.txt', because I am using NuScenes database to train F-ConvNet, and NuScenes provide scripts to convert data structure into Kitti one, so I already generate 'train.txt' and 'val.txt' for NuScenes by myself, but I don't know how to generate 'rgb_detection_val.txt'.

**Comment by zhixinwang** [comment]
We directly use the ground truth 2D results during training, but in our final evaluation, we get the final 3D detection results basing on 2D detectors.  And "frustum_caronly_val_rgb_detection.pickle" is the file generating from "rgb_detection_val.txt".

The formal of "rgb_detection_val.txt" is "Image ID, Category ID, Score, Box (x1, y1, x2, y2)". You can see the source code [here](https://github.com/zhixinwang/frustum-convnet/blob/a096d402e11965dad9745a7600a6ef98f72f2bf8/kitti/prepare_data.py#L420) to understand the usage. So, for NuScene dataset, you also need a 2D detector to provide the 2D detection results and save them in above format.
