### ISSUE TITLE
reported sunrgbd result

### ISSUE THREAD

**Issue by timetomakesense** [zhixinwang/frustum-convnet#8]
Hi,

Thanks for your work. I want to evaluate the network on the sunrgbd dataset. I was wondering how do you evaluate the model on the SUN RGBD dataset. It seems that f pointnet does not provide 2d detection results for sun rgbd dataset. Did you train your own rgb detector on the sunrgbd dataset, or use the gt boxes?

Best

**Comment by zhixinwang** [comment]
We train faster-rcnn with the backbone network fo ResNet50 to provide the 2D detection results of SUNRGBD. We get a similar 2D detection result as f-poinnets.  The reported results are based on this 2D detector.
If we use the ground truth 2D boxes, we can get a very high 3D detection mAP.

**Comment by timetomakesense** [comment]
Hi zhixin,
thank you for your reply. Would you mind share your mAP on SUN RGB-D under IoU 0.5? I would like to make a comparison while cannot find that in your paper

**Comment by zhixinwang** [comment]
I have replyed your email.

**Comment by zx970505** [comment]
hi, i want to know how to visualize the output of SUNRGBD ? please help me @zhixinwang @timetomakesense
