### ISSUE TITLE
How to test on pedestrian and cyclist class?

### ISSUE THREAD

**Issue by gujiaqivadin** [zhixinwang/frustum-convnet#9]
Hello, zhixinwang!
    Thanks for your great work on frustum convnet. I found that there is only configs code for car training, if I want to test the performance on people class, what do I need to change in scripts or configs files.

**Comment by aks1087** [comment]
Hello @zhixinwang , i too have a similar question. Does your git repo cover implementation for cyclists and pedestrians too? how to train and test for those objects?

**Comment by zhixinwang** [comment]
Sorry, current release version does not include the implementation for pedestrains and cyclists.
If you want to train pedestrians and cyclists,  you can follow the same step during training the car model, but you need to change some config settings, such as  'CAR_ONLY=False,PEOPLE_ONLY=True', 'IOU_THRESH=0.5', and the STRIDE and HEIGHT_HALF parameters according to our paper.

**Comment by Sreeni1204** [comment]
@zhixinwang 

The above config changes mentioned for performing the train and validation on Pedestrian and Cyclist classes, are these changes enough or do we need to change something in code?

And we need to perform the above changes in "det_sample.yaml" and "refine_car.yaml" files? or any other changes required?

**Comment by zhixinwang** [comment]
I think changes  of the config in `*.yaml` is enough. 
The most import settings you need to change are  STRIDE and HEIGHT_HALF. For reference, in the first stage,  STRIDE: (0.1, 0.2, 0.4, 0.8),  HEIGHT_HALF: (0.1, 0.2, 0.4, 0.8), and refine stage is STRIDE: (0.05, 0.1, 0.2, 0.4), HEIGHT_HALF: (0.05, 0.1, 0.2, 0.4) for people category.

**Comment by Sreeni1204** [comment]
Thank you for the response.

I do have another question to clarify!

The variable MAX_DEPTH - what is it used for? is it to limit the range of LiDAR data or it has some other significance?
